version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez satış verileri
        # Freshness uyarısını gidermek için config altına alındı
        config:
          freshness:
            warn_after:
              count: 90
              period: day
          loaded_at_field: CAST(date_date AS TIMESTAMP)

        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orders_id
                - pdt_id
        columns:
          - name: date_date
            description: Date of purchase
          - name: orders_id
            description: Foreign key to ship
          - name: pdt_id
            description: Foreign key to product
          - name: revenue
            description: Revenue = quantity * selling_price
          - name: quantity
            description: Quantity purchased for the order
      


      - name: product
        identifier: raw_gz_product
        description: Products of Greenweez
        columns:
          - name: products_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: Purchase price of the product

      - name: ship
        identifier: raw_gz_ship
        description: Shipping data for Greenweez orders
        columns:
          - name: orders_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: Shipping fee paid by customer
          - name: log_cost
            description: Logistics cost
          - name: ship_cost
            description: Shipping cost paid to carrier
  
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
        
models:
        
  - name: int_campaigns
    description: tüm kampanyalardan gelen veriler
    columns:
      - name: paid_source
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null

  - name: int_campaigns_day
    description: Tüm kampanyaların toplu günlük verisi
    columns:
      - name: paid_source
        tests:
          - not_null

  - name: finance_campaigns_day
    description: global_kpi
    columns:
      - name: ads_margin
        description: operational_margin-ads_cost
        tests:
          - not_null
      - name: average_basket
        description: :her gün için ortalama sepet tutarı
        tests:
          - not_null
  - name: finance_campaigns_month
    description: ay bazlı global kpi